[window]
dimensions = { columns = 80, lines = 24 }
position = { x = 50, y = 50 }
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 1.0
decorations = "full"
startup_mode = "Windowed"

[font]
normal = { family = "HackGen35 Console", style = "Regular" }
size = 12
offset = { x = 0, y = 0 }

[general]
import = ["themes/dark.toml"]
live_config_reload = true

[cursor]
style = "Beam"
blink_interval = 500

[env]
HYPRLAND_CURSOR_THEME = "Breeze_Snow"
HYPRLAND_CURSOR_SIZE = "24"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[scrolling]
# Number of lines in the scrollback buffer
history = 100000
# Scrolling speed multiplier for mouse wheel and key scrolls
multiplier = 3

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"
