wallpaper {
    monitor = eDP-1
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-7
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/yuwki0131/myconfig/wallpapers/wallpaper.jpg
    fit_mode = cover
}
