#####################
# Initialize Session

# init session
exec-once = bash ~/.config/hypr/scripts/session-init.sh
exec-once = fcitx5
exec-once = hyprpaper
exec-once = eww open bar
# exec-once = hyprctl setcursor Bibata-Modern-Ice 24
