#####################
# Window Rules

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule with match props
# windowrule = float on, match:class kitty, match:title kitty
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# terminal/editor opacity
windowrule = opacity 0.8 0.7, match:class st-256color
windowrule = opacity 0.9 0.8, match:class kitty
windowrule = opacity 0.9 0.8, match:class Alacritty
windowrule = opacity 0.8 0.7, match:class emacs
