name: Nix Flake Check

on:
  push:
    branches:
      - master
      - work
      - codex/*
      - feature/*
  pull_request:
    branches:
      - master
      - work
      - codex/*
      - feature/*
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - name: Prepare hardware configuration
        run: |
          sudo mkdir -p /etc/nixos
          sudo cp ./testfiles/hardware-configuration.nix /etc/nixos
      - name: Run flake check
        run: |
          nix flake check --impure
