name: NixOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - name: Build NixOS configuration
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel
